---
title: "simulation_all_unknown"
author: "Anil Battalahalli Sreenath"
date: "12/9/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import stuff

```{r}
set.seed(84884)
library(expint)
library(remotes)
library(sigmoid)
```

## Accept-Rejection sampling to generate Power Law samples with Exponential Cutoff

```{r}
alpha <- 2.2
lambda <- 0.3
xmin <- 1.1

theta_true <- c(alpha, lambda, xmin)

c <-  lambda^(1-alpha)/(gammainc(1-alpha, lambda*xmin))
```

PDF of Power Law with Exponential Distribution

```{r}
fp <- function(x){
  if (x > xmin){
  return(c * ((x^ (-1 * alpha)) * (exp(-1 * lambda * x))))
  }
  else {
    return(0)
  }
}
```

Covering distribution

```{r}
foo <- function(xmin, alpha){
  u <- runif(1,0,1)
  return(xmin*((1-u)^(1/(1-alpha))))
}

generate <- function(n, xmin, alpha){
  return(as.numeric(replicate(n, foo(xmin, alpha), simplify=FALSE)))
}

getCumulative <- function(x, xmin, alpha){
  return(1-((x/xmin)^(1-alpha)))
}

covering <- function(i){
  return(generate(1, xmin, alpha))
}
```

```{r}
c_c <- ((alpha-1)/xmin) * (xmin^alpha)
covering_pdf <- function(x){
  if (x > xmin){
    return(((alpha-1)/xmin)*((x/xmin)^(-alpha)))
    }
  else{
    return(0)
  }
}
```

```{r}

M <- c*(exp(-lambda*(xmin)))/c_c
```

```{r}
compute_ratio <- function(u){
  return(fp(u)/(M*covering_pdf(u)))
}
```

Accept-Reject Sampling

```{r}
samples <- list()
for (i in 1:500){
  sample <- covering()
  r <- compute_ratio(sample)
  result <- rbinom(1,1,prob=r)
  if (result == 1){
    samples <- c(samples, sample)
  }
}
samplesPL <- as.numeric(samples)
length(samplesPL)
```


```{r}
plot(density(samplesPL), xlab = "x", ylab = "Frequency", main="Density")
```

1.  Alpha: Unif (2,3)
2.  Lambda: exp(10) (1,3)
3.  xmin: exp(10) (1,3)

```{r}
prior_alpha <- function(a){
  if (a >= 2 && a <= 3) {
    return(dexp(a, 15))
  } else{
    return(0)
  }
}
```

```{r}
prior_lambda <- function(l) {
  if (l >= 1e-16 && l <= 3) {
    return(dexp(l, 10))
  } else{
    return(0)
  }
}
```

```{r}
prior_xmin <- function(x) {
  if (x >= 1 && x <= 3) {
    return(dexp(x, 20))
  } else{
    return(0)
  }
}
```

```{r}
proposal <- function(given){
  a <- rexp(1, given[1])
  l <- rexp(1, given[2])
  x <- rexp(1, given[3])
  return(c(a,l,x))
}
```

```{r}
proposal_pdf <- function(this, given){
  a <- dexp(this[1], given[1])
  l <- dexp(this[2], given[2])
  x <- dexp(this[3], given[3])
  return(a*l*x)
}
```

Likelihood function

```{r}
pllikelihood <- function(x, alpha, lambda, xmin){
  if (x > xmin){
    return(((x^ (-alpha)) * exp(-lambda * x) * (lambda^(1 - alpha)))/suppressWarnings(gammainc(1-alpha, lambda * xmin)))
  }
  else {
    return(1)
  }
}
```

```{r}
loglikelihood <- function(data, alpha, lambda, xmin){
  lik <- lapply(data, pllikelihood,  alpha=alpha, lambda=lambda, xmin=xmin)
  blee <- lapply(lik, log)
  return(sum(as.numeric(blee)))
}
```

Posterior distribution known up to a constant

```{r}
logpostfunc <- function(data, theta){
  alpha = theta[1]
  lambda = theta[2]
  xmin = theta[3]
  return(loglikelihood(data, alpha, lambda, xmin)+log(prior_alpha(alpha))+log(prior_xmin(xmin))+log(prior_lambda(lambda)))
}
```

Metropolis-Hasting for Bayesian Inference

```{r}
reps <- 100
params <- list()
pb = txtProgressBar(min = 1, max = reps, initial = 1)
for (v in 1:reps){
  nit <- 100
  accepted <- 0
  theta <- list()
  theta[[1]] <- proposal(c(2.1, 0.9, 1.3))
  for(i in 2:nit){
    theta_star <- proposal(theta[[i-1]])
    a = (logpostfunc(samplesPL, theta_star) + log(proposal_pdf(theta[[i-1]],
        theta_star)))-logpostfunc(samplesPL,theta[[i-1]]) - log(proposal_pdf(theta_star,theta[[i-1]]))
    a <- exp(a)
    if (is.nan(a)){
      theta[[i]] <-  theta[[i-1]]
    } else if (a > 1){
      theta[[i]] <-  theta_star
      accepted <- accepted+1
    } else{
      r = rbinom(1,1,a)
      if (r == 1){
        theta[[i]] <-  theta_star
        accepted <- accepted+1
      } else{
        theta[[i]] <-  theta[[i-1]]
      }
    }
  }
  post_pdf <- lapply(theta, logpostfunc, data=samplesPL)
  theta_selected <- theta[[which.max(post_pdf)]]
  params[[v]] <- theta_selected
  setTxtProgressBar(pb,v)
}
```


```{r}
get_item <- function(a,i){
  return(a[i])
}
```

```{r}
gett <- function(l,index){
  as.numeric(lapply(l, get_item, i=index))
}
```

```{r}
d <- density(gett(params,1))
i = which.max(d$y)
d$x[i]
```

```{r}
plot(d, xlab = "alpha", ylab = "Density", main = "Density of alpha on the posterior")
abline(v=d$x[i], col="blue")
abline(v=alpha, col="red")
```

```{r}
mean(gett(params,1))
```


```{r}
d <- density(gett(params,2))
i = which.max(d$y)
d$x[i]
```

```{r}
plot(d, xlab = "lambda", ylab = "Density", main = "Density of lambda on the posterior")
abline(v=d$x[i], col="blue")
abline(v=lambda, col="red")
```

```{r}
mean(gett(params,2))
```



```{r}
d <- density(gett(params,3))
i = which.max(d$y)
d$x[i]
```

```{r}
plot(d, xlab = "xmin", ylab = "Density", main = "Density of xmin on the posterior")
abline(v=d$x[i], col="blue")
abline(v=xmin, col="red")
```

```{r}
mean(gett(params,3))
```

```{r}
ppp <- data.frame(alpha=gett(params,1), lambda=gett(params,2), xmin=gett(params,3))
write.csv(ppp, "case_3_params.csv")
```

